baseURL = "https://racheltsai.xyz/"
languageCode = "en-us"
title = "huh?"

enableEmoji = true

theme = "PaperMod"

[params]

[params.homeInfoParams]
Title = "Hi! 👋 I'm Rachel."
Content = "what are we doing today? :)"

[[params.socialIcons]]
name = "linkedin"
title = "View LinkedIn Profile"
url = "https://www.linkedin.com/in/racheltsai/"

[[params.socialIcons]]
name = 'github'
title = "View Github Profile"
url = "https://github.com/tsai-duck"

defaultTheme = "auto"
# ShowPostNavLinks = true
# ShowBreadCrumbs = true
